version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: medusa-db
    restart: always
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: medusa-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
